/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package capa_vistas;

import capalogica.usuario;
import javax.swing.JOptionPane;

/**
 *
 * @author SEBASTIAN
 */
public class consultar_usuario extends javax.swing.JFrame {

    /**
     * 
     * Creates new form consultar_usuario
     */
    public consultar_usuario() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtnombreb = new javax.swing.JTextField();
        txtedadb = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtapellidob = new javax.swing.JTextField();
        txtcelularb = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Consulta de Usuarios");
        setMinimumSize(new java.awt.Dimension(700, 600));
        getContentPane().setLayout(null);

        jLabel1.setText("Nombre:");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(82, 85, 60, 14);

        jButton1.setText("Buscar ");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(69, 301, 80, 23);

        jButton2.setText("Regresar ");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(317, 301, 100, 23);

        jLabel2.setText("edad:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(90, 150, 45, 14);

        jLabel3.setText("celular:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(90, 190, 58, 14);

        txtnombreb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnombrebActionPerformed(evt);
            }
        });
        getContentPane().add(txtnombreb);
        txtnombreb.setBounds(180, 80, 160, 20);
        getContentPane().add(txtedadb);
        txtedadb.setBounds(180, 150, 160, 20);

        jLabel4.setText("Apellido:");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(82, 119, 60, 14);

        txtapellidob.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtapellidobActionPerformed(evt);
            }
        });
        getContentPane().add(txtapellidob);
        txtapellidob.setBounds(180, 120, 160, 20);
        getContentPane().add(txtcelularb);
        txtcelularb.setBounds(180, 190, 160, 20);

        jLabel7.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("consultar usuarios ");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(130, 20, 330, 29);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/3ROwbF.png"))); // NOI18N
        jLabel5.setText("jLabel5");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(0, 0, 270, 580);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/227c4ef522c153f2be5e4b9ede97d191.jpg"))); // NOI18N
        jLabel6.setText("jLabel6");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(260, 0, 430, 570);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtapellidobActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtapellidobActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtapellidobActionPerformed

    private void txtnombrebActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnombrebActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnombrebActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
      
        int resultado=0;        

            usuario t = new usuario();
            usuario e = new usuario();
            e=t.buscar(txtnombreb.getText());
            txtnombreb.setText(e.getnombreu());
            txtapellidob.setText(e.getapellidou());
            txtedadb.setText(e.getedadu());
            txtcelularb.setText(e.getcelularu());
            if(txtcelularb.getText().equals(""))
                   JOptionPane.showMessageDialog(null, "no existe");
            
      
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        login v=new login();
        v.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(consultar_usuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(consultar_usuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(consultar_usuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(consultar_usuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new consultar_usuario().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField txtapellidob;
    private javax.swing.JTextField txtcelularb;
    private javax.swing.JTextField txtedadb;
    private javax.swing.JTextField txtnombreb;
    // End of variables declaration//GEN-END:variables
}
