/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package capa_vistas;

import capalogica.usuario;
import javax.swing.JOptionPane;

/**
 *
 * @author SEBASTIAN
 */
public class login extends javax.swing.JFrame {

    /**
     * Creates new form login
     */
    public login() {
       
        initComponents();
         jLabel2.setText("Putito");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        txtusuariou = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        btnlogin = new javax.swing.JButton();
        btnvolver = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtclave = new javax.swing.JPasswordField();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("ingreso casa domotica");
        setLocation(new java.awt.Point(300, 300));
        setMinimumSize(new java.awt.Dimension(500, 500));
        getContentPane().setLayout(null);

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("usuario:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(40, 210, 90, 14);

        txtusuariou.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtusuariouActionPerformed(evt);
            }
        });
        txtusuariou.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtusuariouKeyTyped(evt);
            }
        });
        getContentPane().add(txtusuariou);
        txtusuariou.setBounds(130, 200, 230, 30);

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("clave:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(50, 260, 80, 30);

        btnlogin.setText("ingresar");
        btnlogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnloginActionPerformed(evt);
            }
        });
        getContentPane().add(btnlogin);
        btnlogin.setBounds(120, 310, 200, 20);

        btnvolver.setText("volver");
        btnvolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnvolverActionPerformed(evt);
            }
        });
        getContentPane().add(btnvolver);
        btnvolver.setBounds(390, 360, 73, 20);

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/para la contraseña.jpg"))); // NOI18N
        getContentPane().add(jLabel9);
        jLabel9.setBounds(330, 270, 30, 30);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/para el usuario.jpg"))); // NOI18N
        getContentPane().add(jLabel5);
        jLabel5.setBounds(100, 200, 30, 30);

        jLabel7.setFont(new java.awt.Font("Agency FB", 2, 36)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/imagen vista .jpg"))); // NOI18N
        jLabel7.setText("ingreso de usuario");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(70, 60, 380, 80);

        txtclave.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtclaveKeyTyped(evt);
            }
        });
        getContentPane().add(txtclave);
        txtclave.setBounds(100, 270, 230, 30);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/LOGIN SSSS.jpg"))); // NOI18N
        jLabel4.setText("jLabel4");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(-200, -140, 1160, 710);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtusuariouActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtusuariouActionPerformed
    
    
    }//GEN-LAST:event_txtusuariouActionPerformed

    private void btnvolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnvolverActionPerformed
        // TODO add your handling code here:
        vistaprincipal1 v=new vistaprincipal1();
        v.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnvolverActionPerformed

    private void btnloginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnloginActionPerformed
        // TODO add your handling code here:// verifica el usuario y lo deja ingresar a la ventana menu
            // TODO add your handling code here:
        //vALIDAR USUARIO
           int Resultado=0;
          
           usuario t = new usuario();
            Resultado =t.Login(txtusuariou.getText(), txtclave.getText());
            if (Resultado == 1){
                funciones invocar =new funciones();
                invocar.setVisible(true);
                this.setVisible(false);
           
            }else{
               JOptionPane.showMessageDialog(null, "login fallido intente de nuevo");
            }
            
           
             
    }//GEN-LAST:event_btnloginActionPerformed

    private void txtusuariouKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtusuariouKeyTyped
        // TODO add your handling code here:
        char x;
    x = evt.getKeyChar();
    if (x >= '0' && x <= '9') {
        evt.consume();
    }
        if(txtusuariou.getText().length() >=10){
             evt.consume();
              } 
                         
        
    }//GEN-LAST:event_txtusuariouKeyTyped

    private void txtclaveKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtclaveKeyTyped
        // TODO add your handling code here:
        if(txtclave.getText().length() >=10){
             evt.consume();
              } 
            
    }//GEN-LAST:event_txtclaveKeyTyped

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        <editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        </editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new login().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnlogin;
    private javax.swing.JButton btnvolver;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPasswordField txtclave;
    private javax.swing.JTextField txtusuariou;
    // End of variables declaration//GEN-END:variables
}
