/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package capa_vistas;

import capalogica.usuario;
import javax.swing.JOptionPane;

/**
 *
 * @author SEBASTIAN
 */
public class Registrarusuario extends javax.swing.JFrame {

    /**
     * Creates new form Registrarusuario
     */
    public Registrarusuario() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnregistrar = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        txtnombreu = new javax.swing.JTextField();
        txtapellidou = new javax.swing.JTextField();
        txtedadu = new javax.swing.JTextField();
        btnvolver = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtcontraseñau = new javax.swing.JPasswordField();
        txtverificacionu = new javax.swing.JPasswordField();
        jLabel10 = new javax.swing.JLabel();
        txtcelularu = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtusuariou = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/3ROwbF.png"))); // NOI18N
        jLabel5.setText("jLabel5");

        jLabel12.setText("jLabel12");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Registro Casa Domotica ");
        setLocation(new java.awt.Point(300, 300));
        setMinimumSize(new java.awt.Dimension(500, 700));
        getContentPane().setLayout(null);

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Nombre:");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(60, 160, 70, 20);

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Edad:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(60, 270, 55, 14);

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Contraseña:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(60, 330, 100, 14);

        btnregistrar.setText("registrar");
        btnregistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnregistrarActionPerformed(evt);
            }
        });
        getContentPane().add(btnregistrar);
        btnregistrar.setBounds(320, 440, 120, 23);

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Apellido:");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(60, 210, 80, 14);

        txtnombreu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnombreuActionPerformed(evt);
            }
        });
        txtnombreu.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtnombreuKeyTyped(evt);
            }
        });
        getContentPane().add(txtnombreu);
        txtnombreu.setBounds(170, 160, 230, 20);

        txtapellidou.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtapellidouKeyTyped(evt);
            }
        });
        getContentPane().add(txtapellidou);
        txtapellidou.setBounds(170, 200, 230, 20);

        txtedadu.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtedaduKeyTyped(evt);
            }
        });
        getContentPane().add(txtedadu);
        txtedadu.setBounds(170, 270, 230, 20);

        btnvolver.setText("volver");
        btnvolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnvolverActionPerformed(evt);
            }
        });
        getContentPane().add(btnvolver);
        btnvolver.setBounds(60, 440, 140, 23);

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Verificacion:");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(60, 370, 100, 14);

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Registrar Usuario");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(110, 50, 400, 70);

        txtcontraseñau.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtcontraseñauKeyTyped(evt);
            }
        });
        getContentPane().add(txtcontraseñau);
        txtcontraseñau.setBounds(170, 330, 230, 20);

        txtverificacionu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtverificacionuActionPerformed(evt);
            }
        });
        txtverificacionu.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtverificacionuKeyTyped(evt);
            }
        });
        getContentPane().add(txtverificacionu);
        txtverificacionu.setBounds(170, 370, 230, 20);

        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("celular:");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(60, 240, 40, 14);

        txtcelularu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcelularuActionPerformed(evt);
            }
        });
        txtcelularu.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtcelularuKeyTyped(evt);
            }
        });
        getContentPane().add(txtcelularu);
        txtcelularu.setBounds(170, 240, 230, 20);

        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("usuario:");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(60, 300, 70, 14);

        txtusuariou.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtusuariouKeyTyped(evt);
            }
        });
        getContentPane().add(txtusuariou);
        txtusuariou.setBounds(170, 300, 230, 20);

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/registrar usuarios.jpg"))); // NOI18N
        jLabel11.setText("jLabel11");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(30, 50, 70, 60);

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/registrar usuario_1.jpg"))); // NOI18N
        jLabel13.setText("jLabel13");
        getContentPane().add(jLabel13);
        jLabel13.setBounds(-50, 10, 690, 730);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnvolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnvolverActionPerformed
        // TODO add your handling code here:
        vistaprincipal1 v =new vistaprincipal1();
        v.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnvolverActionPerformed

    private void txtverificacionuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtverificacionuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtverificacionuActionPerformed

    private void txtnombreuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnombreuActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_txtnombreuActionPerformed

    private void btnregistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnregistrarActionPerformed
        // TODO add your handling code here:
        if (txtcontraseñau.getText().equals(txtverificacionu.getText())){
            usuario t = new usuario();
                t.setnombreu(txtnombreu.getText());
                t.setapellidou(txtapellidou.getText());
                t.setedadu(txtedadu.getText());
                t.setcelularu(txtcelularu.getText());
                t.setusuariou(txtusuariou.getText());
                t.setclaveu(txtcontraseñau.getText());
                t.setconfirmacionu(txtverificacionu.getText());
                if(t.registrarusuario()){
                      JOptionPane.showMessageDialog(this,"El usuario a sido creado con exito.\n");
                      vistaprincipal1 invocar =new vistaprincipal1();
                      invocar.show();
                      this.dispose();
                }else{
                    JOptionPane.showMessageDialog(this, "Error en la creacion de usuario\n");
                }
     }else{
        JOptionPane.showMessageDialog(this, "las contraseñas no coinciden.\n");
     }
        
    }//GEN-LAST:event_btnregistrarActionPerformed

    private void txtnombreuKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtnombreuKeyTyped
        // TODO add your handling code here:
        char x;
    x = evt.getKeyChar();
    if (x >= '0' && x <= '9') {
        evt.consume();
    }
        if(txtnombreu.getText().length() >=15){
             evt.consume();
              }
    }//GEN-LAST:event_txtnombreuKeyTyped

    private void txtcelularuKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtcelularuKeyTyped
        // TODO add your handling code here:
       char x;
    x = evt.getKeyChar();
    if ((x >= 'a' && x <= 'z') || (x >= 'A' && x <= 'Z')) {
        evt.consume();
    }
   
        if(txtcelularu.getText().length() >=10){
             evt.consume();
              } 
    }//GEN-LAST:event_txtcelularuKeyTyped

    private void txtcelularuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcelularuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcelularuActionPerformed

    private void txtapellidouKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtapellidouKeyTyped
        // TODO add your handling code here:
         char x;
    x = evt.getKeyChar();
    if (x >= '0' && x <= '9') {
        evt.consume();
    }
        if(txtapellidou.getText().length() >=15){
             evt.consume();
              }
                        
    }//GEN-LAST:event_txtapellidouKeyTyped

    private void txtedaduKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtedaduKeyTyped
        // TODO add your handling code here:
        char x;
    x = evt.getKeyChar();
    if ((x >= 'a' && x <= 'z') || (x >= 'A' && x <= 'Z')) {
        evt.consume();
    }
   
        if(txtedadu.getText().length() >=2){
             evt.consume();
              } 
    }//GEN-LAST:event_txtedaduKeyTyped

    private void txtusuariouKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtusuariouKeyTyped
        // TODO add your handling code here:
         char x;
    x = evt.getKeyChar();
    if (x >= '0' && x <= '9') {
        evt.consume();
    }
        if(txtusuariou.getText().length() >=10){
             evt.consume();
              } 
    }//GEN-LAST:event_txtusuariouKeyTyped

    private void txtcontraseñauKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtcontraseñauKeyTyped
        // TODO add your handling code here:
         if(txtcontraseñau.getText().length() >=10){
             evt.consume();
              } 
    }//GEN-LAST:event_txtcontraseñauKeyTyped

    private void txtverificacionuKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtverificacionuKeyTyped
        // TODO add your handling code here:
         if(txtverificacionu.getText().length() >=10){
             evt.consume();
              } 
    }//GEN-LAST:event_txtverificacionuKeyTyped

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(Registrarusuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(Registrarusuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(Registrarusuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(Registrarusuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new Registrarusuario().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnregistrar;
    private javax.swing.JButton btnvolver;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField txtapellidou;
    private javax.swing.JTextField txtcelularu;
    private javax.swing.JPasswordField txtcontraseñau;
    private javax.swing.JTextField txtedadu;
    private javax.swing.JTextField txtnombreu;
    private javax.swing.JTextField txtusuariou;
    private javax.swing.JPasswordField txtverificacionu;
    // End of variables declaration//GEN-END:variables
}
